# Database configuration
database:
  name: experiment_tracking_new
  user: ''  # Change this to your database user
  password: ''    # Change this to your database password
  host: localhost

# Paths configuration
paths:
  root: data
  train_data: datasets/original/mnist_train.pt
  test_data: datasets/original/mnist_test.pt
  train_data_blurred: datasets/blurred/mnist_train_blurred.pt
  test_data_blurred: datasets/blurred/mnist_test_blurred.pt
  models: models  # Directory for saved models

# Data preparation settings
data_prep:
  blur_sigma: 2.0
  seed: 42  # Random seed for reproducibility
  num_workers: 4  # Number of workers for data loading

# Model configurations
model_configs:
  default:
    name: "default"
    hidden_size: 128
    batch_size: 64
    learning_rate: 0.01
    data_split_ratio: 0.8
    max_epochs: 10
    max_samples: null
    
  small_hidden:
    name: "small_hidden"
    hidden_size: 2
    batch_size: 64
    learning_rate: 0.01
    data_split_ratio: 0.8
    max_epochs: 10
    max_samples: null
    
  small_dataset:
    name: "small_dataset"
    hidden_size: 128
    batch_size: 64
    learning_rate: 0.01
    data_split_ratio: 0.8
    max_epochs: 10
    max_samples: 100
    
  blurred_dataset:
    name: "blurred_dataset"
    hidden_size: 128
    batch_size: 64
    learning_rate: 0.01
    data_split_ratio: 0.8
    max_epochs: 10
    max_samples: null

# Testing configuration
testing:
  batch_size: 64
  save_predictions: true
  shuffle: false